{{ if .Values.createServiceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding }}
  namespace: {{ .Values.clusterRoleNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
{{ end }}